name: Move branchs issue to QA 
'on':
  push:
    branches:
      - dev
jobs:
  login-to-jira:
    runs-on: ubuntu-latest
    steps:
      - uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: '${{ secrets.JIRA_BASE_URL }}'
          JIRA_USER_EMAIL: '${{ secrets.JIRA_USER_EMAIL }}'
          JIRA_API_TOKEN: '${{ secrets.JIRA_API_TOKEN }}'
      - uses: atlassian/gajira-find-issue-key@v3
        with:
          from: branch
        id: issue
      - uses: tuanddd/jira-automate-transition@v1.0.5
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          column-to-move-to-when-merged: QA
          jira-issue-id: '${{ steps.issue.outputs.issue_key }}'
